### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by kklok** [junalmeida/docker-mono-web#5] opened 2019-10-03 12:26 UTC
Tried the following:
git clone https://github.com/junalmeida/docker-mono-web.git
cd ./docker-mono-web/sample
docker-compose build
docker-compose up

go to http://localhost - getting 404:

Runtime error
The resource cannot be found.

Description: HTTP 404.The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. Please review the following URL and make sure that it is spelled correctly.
Details: No virtual path information available.
Exception stack trace:

Did I do something wrong?

**Comment by junalmeida** [comment] 2019-10-06 11:53
What is your host operating system? If you are using docker-machine, or docker tools for virtual box on a Windows host, please make sure that you cloned this repository under your home dir, and check if a container can fully access your file system. Try to open bash into the container to see if all files are accessbile from inside.

**Comment by junalmeida** [comment] 2019-10-06 11:54
This is probably a dupe of #3 , let me know.

**Comment by kklok** [comment] 2019-10-06 14:08
The problem was with this line:
fastcgi_index Default.aspx;
should be
fastcgi_index /;

**Closed as completed** 2020-05-16 18:08 UTC
